# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: '#research'
    weight: 10
  - name: Featured
    url: '#projects'
    weight: 20
  - name: Publication
    url: '#Publication'
    weight: 30
  - name: Awards
    url: '#awards-and-honors'
    weight: 40
  - name: Patents
    url: '#patents'
    weight: 50
  - name: Gallery
    url: '#gallery'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
